<script setup lang="ts">
import { computed, ref, type Ref } from "vue";
import { useDataStore } from "../stores/data";
import type { BaseRecord, ImportFile, RuleRecord, TermRecord } from "../types";
type ImportKind="terms"|"rules"|"base";
interface Workspace{label:string;subject:string;description:string;directory:Ref<FileSystemDirectoryHandle|undefined>;files:Ref<ImportFile[]>;}
const extensions=[".doc",".docx",".xls",".xlsx",".csv",".tsv",".pdf",".txt",".md",".json",".xml",".rtf",".odt",".ods",".ppt",".pptx"];
const labels:Record<string,string>={doc:"Word 文档",docx:"Word 文档",xls:"Excel 表格",xlsx:"Excel 表格",csv:"CSV 数据",tsv:"TSV 数据",pdf:"PDF 文档",txt:"文本文件",md:"Markdown",json:"JSON 数据",xml:"XML 数据",rtf:"RTF 文档",odt:"OpenDocument",ods:"OpenDocument",ppt:"演示文稿",pptx:"演示文稿"};
const ext=(name:string)=>name.split(".").pop()?.toLowerCase()??"";const formatSize=(bytes:number)=>bytes<1024?`${bytes} B`:bytes<1048576?`${(bytes/1024).toFixed(1)} KB`:`${(bytes/1048576).toFixed(1)} MB`;
const store=useDataStore();const activeKind=ref<ImportKind>("terms");const picker=ref<HTMLInputElement>();const dragging=ref(false);
const termDirectory=ref<FileSystemDirectoryHandle>();const ruleDirectory=ref<FileSystemDirectoryHandle>();const baseDirectory=ref<FileSystemDirectoryHandle>();
const termFiles=ref<ImportFile[]>([]);const ruleFiles=ref<ImportFile[]>([]);const baseFiles=ref<ImportFile[]>([]);
const messages=ref<Record<ImportKind,string>>({terms:"",rules:"",base:""});
const workspaces:Record<ImportKind,Workspace>={terms:{label:"术语导入",subject:"术语",description:"自动映射为术语库标准字段并保存标准化结果",directory:termDirectory,files:termFiles},rules:{label:"规则导入",subject:"规则",description:"自动映射为规则库标准字段并保存标准化结果",directory:ruleDirectory,files:ruleFiles},base:{label:"基础数据导入",subject:"基础数据",description:"自动归类专业分类、计量单位、缩写与数据来源",directory:baseDirectory,files:baseFiles}};
const current=computed(()=>workspaces[activeKind.value]);const readyCount=computed(()=>current.value.files.value.filter(x=>x.status==="ready"||x.status==="error").length);
function switchKind(kind:ImportKind){activeKind.value=kind;dragging.value=false;}
async function chooseDirectory(){if(!window.showDirectoryPicker){messages.value[activeKind.value]="当前浏览器不支持目录写入，请使用最新版 Chrome 或 Edge。";return;}try{current.value.directory.value=await window.showDirectoryPicker({mode:"readwrite"});messages.value[activeKind.value]=`保存目录已设置：${current.value.directory.value.name}`;}catch(error){if((error as DOMException).name!=="AbortError")messages.value[activeKind.value]="无法获得目录写入权限。";}}
function add(input:FileList|File[]){const all=Array.from(input),valid=all.filter(file=>extensions.includes(`.${ext(file.name)}`)),list=current.value.files.value,seen=new Set(list.map(x=>`${x.file.name}-${x.file.size}-${x.file.lastModified}`));list.push(...valid.filter(file=>!seen.has(`${file.name}-${file.size}-${file.lastModified}`)).map(file=>({id:crypto.randomUUID(),file,category:labels[ext(file.name)]??"数据文件",status:"ready" as const})));messages.value[activeKind.value]=all.length>valid.length?`${all.length-valid.length} 个不支持的文件已忽略`:"";if(picker.value)picker.value.value="";}
function onDrop(event:DragEvent){event.preventDefault();dragging.value=false;if(event.dataTransfer)add(event.dataTransfer.files);}
function csvRows(text:string,separator:string){const lines=text.replace(/^\uFEFF/,"").split(/\r?\n/).filter(Boolean);if(!lines.length)return[];const split=(line:string)=>{const out:string[]=[];let value="",quoted=false;for(let i=0;i<line.length;i++){const c=line[i];if(c==='"'&&line[i+1]==='"'){value+='"';i++;}else if(c==='"')quoted=!quoted;else if(c===separator&&!quoted){out.push(value.trim());value="";}else value+=c;}out.push(value.trim());return out;};const headers=split(lines[0]);return lines.slice(1).map(line=>Object.fromEntries(headers.map((h,i)=>[h,split(line)[i]??""])));}
const pick=(row:Record<string,unknown>,keys:string[],fallback="")=>{for(const key of keys){const value=row[key];if(value!==undefined&&value!==null&&String(value).trim())return String(value).trim();}return fallback;};
async function rowsFromFile(file:File):Promise<Record<string,unknown>[]> {const extension=ext(file.name);if(extension==="json"){const value=JSON.parse(await file.text());return Array.isArray(value)?value:[value];}if(extension==="csv"||extension==="tsv")return csvRows(await file.text(),extension==="tsv"?'\t':',');if(extension==="docx"){const {default:mammoth}=await import("mammoth");const text=(await mammoth.extractRawText({arrayBuffer:await file.arrayBuffer()})).value;return text.split(/\r?\n/).filter(Boolean).map(name=>({name}));}if(["txt","md","xml"].includes(extension))return (await file.text()).split(/\r?\n/).filter(Boolean).map(name=>({name}));throw new Error(`${extension.toUpperCase()} 原件已保存，但浏览器端暂不能可靠结构化，请转换为 CSV、JSON 或 DOCX 后导入`);}
function next(prefix:string,values:string[],offset:number){return `${prefix}${String(Math.max(0,...values.map(x=>Number(x.replace(/\D/g,""))||0))+offset+1).padStart(4,"0")}`;}
function normalize(kind:ImportKind,rows:Record<string,unknown>[]){if(kind==="terms")return rows.map((row,i):TermRecord=>({id:pick(row,["id","编号"],next("T",store.terms.map(x=>x.id),i)),zh:pick(row,["zh","中文术语","术语","name","名称"]),en:pick(row,["en","英文术语","英文"]),abbr:pick(row,["abbr","缩写"]),domain:pick(row,["domain","专业分类","分类"],"未分类"),subdomain:pick(row,["subdomain","二级分类"],"待整理"),definition:pick(row,["definition","定义","说明"]),unit:pick(row,["unit","单位"]),aliases:pick(row,["aliases","别名"]).split(/[、,;；]/).filter(Boolean),source:pick(row,["source","来源"],"文件导入"),status:"待审核"})).filter(x=>x.zh);if(kind==="rules")return rows.map((row,i):RuleRecord=>({id:pick(row,["id","编号"],next("R",store.rules.map(x=>x.id),i)),name:pick(row,["name","规则名称","名称"]),type:(pick(row,["type","规则类型","类型"],"逻辑关系") as RuleRecord["type"]),domain:pick(row,["domain","专业"],"通用"),severity:(pick(row,["severity","级别"],"警告") as RuleRecord["severity"]),condition:pick(row,["condition","校验条件","条件"]),message:pick(row,["message","提示信息","提示"]),source:pick(row,["source","依据","来源"],"文件导入"),scope:pick(row,["scope","适用范围","范围"],"全部文档"),status:"启用",template:true})).filter(x=>x.name);return rows.map((row,i):BaseRecord=>({id:pick(row,["id","编号"],next("B",store.base.map(x=>x.id),i)),type:(pick(row,["type","类型"],"专业分类") as BaseRecord["type"]),name:pick(row,["name","名称"]),code:pick(row,["code","编码","符号"]),description:pick(row,["description","说明","定义"]),parent:pick(row,["parent","所属分类","分类"],"未分类"),status:"启用"})).filter(x=>x.name);}
async function saveFile(directory:FileSystemDirectoryHandle,fileName:string,data:Blob|string){const handle=await directory.getFileHandle(fileName,{create:true});const writable=await handle.createWritable();await writable.write(data);await writable.close();}
async function importFiles(){const kind=activeKind.value,workspace=workspaces[kind],ready=workspace.files.value.filter(x=>x.status==="ready"||x.status==="error");if(!ready.length)return;if(!workspace.directory.value){messages.value[kind]=`请先选择${workspace.label}的本地保存目录。`;return;}let saved=0,imported=0;const warnings:string[]=[];for(const item of ready){item.status="saving";try{await saveFile(workspace.directory.value,item.file.name,item.file);const rows=await rowsFromFile(item.file);const records=normalize(kind,rows);if(kind==="terms")store.importTerms(records as TermRecord[]);else if(kind==="rules")store.importRules(records as RuleRecord[]);else store.importBase(records as BaseRecord[]);await saveFile(workspace.directory.value,`${item.file.name}.normalized.json`,JSON.stringify(records,null,2));imported+=records.length;item.status="done";saved++;}catch(error){item.status="error";warnings.push((error as Error).message);}}
messages.value[kind]=`${workspace.label}完成：成功 ${saved}/${ready.length} 个文件，已规整并写入 ${imported} 条${workspace.subject}。${warnings.length?` 提示：${warnings[0]}`:""}`;}
function removeFile(id:string){current.value.files.value=current.value.files.value.filter(x=>x.id!==id);}function clearCompleted(){current.value.files.value=current.value.files.value.filter(x=>x.status!=="done");}
</script>
<template><section class="import-page"><div class="page-heading"><div><h1>数据导入</h1><p>三类数据使用独立队列和保存目录，导入时自动规整为目标库字段。</p></div><RouterLink class="home-return" to="/">← 返回首页</RouterLink></div>
<div class="import-tabs" role="tablist"><button v-for="kind in (['terms','rules','base'] as ImportKind[])" :key="kind" :class="{active:activeKind===kind}" role="tab" @click="switchKind(kind)"><span>{{workspaces[kind].label}}</span><b>{{workspaces[kind].files.value.length}}</b></button></div>
<div class="import-workspace"><div class="workspace-heading"><div><h2>{{current.label}}</h2><p>{{current.description}}</p></div><button class="primary" :disabled="!readyCount" @click="importFiles">导入并自动规整</button></div>
<div class="directory-card"><div><strong>{{current.subject}}保存目录</strong><span>{{current.directory.value?.name??'尚未选择目录'}}</span></div><button class="secondary" @click="chooseDirectory">选择目录</button></div>
<div class="drop-zone" :class="{dragging}" role="button" tabindex="0" @dragenter="dragging=true" @dragleave="dragging=false" @dragover.prevent @drop="onDrop" @click="picker?.click()" @keydown.enter="picker?.click()"><div class="upload-icon">⇧</div><strong>拖拽{{current.subject}}文件到此处，或点击选择文件</strong><span>CSV、TSV、JSON、TXT、DOCX 可自动解析；Excel/PDF 先保存原件并提示转换</span><input ref="picker" type="file" multiple :accept="extensions.join(',')" @change="event=>add((event.target as HTMLInputElement).files!)"/></div>
<div class="file-panel"><div class="panel-title"><div><strong>{{current.label}}文件</strong><span>{{current.files.value.length}} 个文件</span></div><button v-if="current.files.value.some(x=>x.status==='done')" class="text-button" @click="clearCompleted">清除已完成</button></div><div v-if="!current.files.value.length" class="empty-list">尚未添加{{current.subject}}文件</div><div v-for="item in current.files.value" v-else :key="item.id" class="file-row"><div class="file-badge">{{ext(item.file.name).toUpperCase()}}</div><div class="file-info"><strong>{{item.file.name}}</strong><span>{{item.category}} · {{formatSize(item.file.size)}}</span></div><span class="status" :class="item.status">{{item.status==='done'?'已规整':item.status==='saving'?'处理中':item.status==='error'?'需处理':'待导入'}}</span><button class="remove" @click="removeFile(item.id)">删除</button></div></div><div v-if="messages[activeKind]" class="message">{{messages[activeKind]}}</div></div></section></template>
