<script setup lang="ts">
import { computed,onMounted,ref } from "vue";import "./PreprocessingPage.css";
interface Item{id:string;file:File;filename:string;size:number;status:"uploading"|"uploaded"|"error";message?:string}
const accept=".xlsx,.xls,.csv,.tsv,.doc,.docx,.txt,.md,.json,.xml,.pdf,.png,.jpg,.jpeg,.webp,.bmp,.tif,.tiff";const staged=ref<File[]>([]),files=ref<Item[]>([]),picker=ref<HTMLInputElement>(),dragging=ref(false),uploading=ref(false);const uploaded=computed(()=>files.value.filter(x=>x.status==="uploaded").length);
const steps=[["结构与字段识别","识别表头、类型、时间、井号、区块和主键"],["标准化与单位换算","统一字段名、单位、日期、编码和缺失值表达"],["缺失数据处理","预留缺失率、插值、统计和模型填补"],["失真与异常检测","预留范围、突变、离群、漂移和一致性检测"],["陈旧数据检测","预留采集时间、标准版本和新鲜度评分"],["结果复核与导出","保留原值、建议值、置信度和人工复核状态"]];
const key=(f:File)=>`${f.name}-${f.size}-${f.lastModified}`;const size=(n:number)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:`${(n/1048576).toFixed(1)} MB`;
function select(input:FileList|File[]){const seen=new Set([...staged.value.map(key),...files.value.map(x=>key(x.file))]);staged.value.push(...Array.from(input).filter(f=>!seen.has(key(f))));if(picker.value)picker.value.value=""}function drop(e:DragEvent){e.preventDefault();dragging.value=false;if(e.dataTransfer)select(e.dataTransfer.files)}
async function upload(){if(!staged.value.length||uploading.value)return;uploading.value=true;const added:Item[]=staged.value.splice(0).map(file=>({id:crypto.randomUUID(),file,filename:file.name,size:file.size,status:"uploading"}));files.value.unshift(...added);for(const item of added){try{const body=new FormData();body.append("file",item.file);const r=await fetch("/api/preprocessing/upload",{method:"POST",body}),data=await r.json() as {filename?:string;size?:number;detail?:string};if(!r.ok)throw new Error(data.detail??"上传失败");item.filename=data.filename??item.filename;item.size=data.size??item.size;item.status="uploaded"}catch(e){item.status="error";item.message=(e as Error).message}}uploading.value=false}
async function restore(){try{const r=await fetch("/api/preprocessing/uploads");if(!r.ok)return;const data=await r.json() as Array<{filename:string;size:number;modified_at:string}>;files.value=data.map(x=>({id:crypto.randomUUID(),file:new File([],x.filename,{lastModified:+new Date(x.modified_at)}),filename:x.filename,size:x.size,status:"uploaded"}))}catch{}}
async function remove(item:Item){if(item.status==="uploaded"){if(!confirm(`确认删除“${item.filename}”吗？`))return;const r=await fetch(`/api/preprocessing/upload/${encodeURIComponent(item.filename)}`,{method:"DELETE"});if(!r.ok){item.message="后台删除失败";return}}files.value=files.value.filter(x=>x.id!==item.id)}onMounted(restore);
</script>
<template><section class="preprocessing-page"><div class="data-heading"><div><h1>数据预处理</h1><p>集中接收工程数据，后续预处理算法将在此执行。</p></div><div class="heading-actions"><span>已上传 {{uploaded}} 个文件</span><RouterLink class="home-return" to="/">← 返回首页</RouterLink></div></div><div class="preprocess-layout"><main><section class="preprocess-card"><header><div><h2>上传待处理数据</h2><p>独立保存到 preprocessing-uploads</p></div><span>最大100 MB/文件</span></header><div class="preprocess-drop" :class="{dragging}" @dragenter.prevent="dragging=true" @dragleave.prevent="dragging=false" @dragover.prevent @drop="drop" @click="picker?.click()"><b>＋</b><strong>选择或拖拽数据文件</strong><span>Excel、CSV、Word、PDF、图片、TXT、JSON、XML</span><input ref="picker" type="file" multiple :accept="accept" @change="e=>select((e.target as HTMLInputElement).files!)"/></div><div v-if="staged.length" class="staged"><span v-for="(f,i) in staged" :key="key(f)">{{f.name}}<button @click="staged.splice(i,1)">×</button></span></div><button class="upload-button" :disabled="!staged.length||uploading" @click="upload">{{uploading?"上传中…":`上传并加入队列（${staged.length}）`}}</button></section><section class="preprocess-card queue"><header><div><h2>预处理文件队列</h2><p>当前仅完成上传管理，尚未执行算法</p></div><span>{{files.length}}项</span></header><p v-if="!files.length" class="empty">尚未上传文件</p><article v-for="item in files" :key="item.id"><i>{{item.filename.split(".").pop()?.toUpperCase()}}</i><div><strong>{{item.filename}}</strong><small>{{size(item.size)}} · {{item.status==="uploaded"?"等待算法":item.status==="uploading"?"上传中":item.message}}</small></div><em>{{item.status==="uploaded"?"待处理":item.status==="uploading"?"上传中":"失败"}}</em><button @click="remove(item)">删除</button></article></section></main><aside class="preprocess-card pipeline"><header><div><h2>算法处理流程</h2><p>获得真实数据后逐项接入</p></div><span>未启用</span></header><ol><li v-for="(step,i) in steps" :key="step[0]"><b>{{i+1}}</b><div><strong>{{step[0]}}</strong><p>{{step[1]}}</p></div><span>待接入</span></li></ol><div class="note">算法不得覆盖原始数据；必须记录任务ID、参数、模型版本、建议值、置信度和复核状态。</div><button disabled>开始预处理（算法待接入）</button></aside></div></section></template>
